# -*- coding: utf-8 -*-
"""first1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ShE0uG7jOpm1rdRYvvGevD2_njd9cNye
"""

print("Hello world")